apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      serviceAccountName: default
      tolerations:
        - operator: Exists
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.2
          ports:
            - name: metrics
              containerPort: 9100
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: k3s-agent-health
          image: curlimages/curl:8.10.1
          command: ["/bin/sh","-c"]
          args:
            - |
              while true; do
                curl -sf http://127.0.0.1:10248/healthz || exit 1
                sleep 30
              done
