#!/bin/bash
set -e

# 1. Instalar RabbitMQ + Erlang
sudo apt update
sudo apt install -y curl gnupg apt-transport-https
curl -fsSL https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb -o erlang.deb
sudo dpkg -i erlang.deb && rm erlang.deb
curl -fsSL https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
sudo apt install -y rabbitmq-server

# 2. Iniciar serviço
sudo systemctl enable rabbitmq-server
sudo systemctl start rabbitmq-server

# 3. Habilitar painel e Prometheus
sudo rabbitmq-plugins enable rabbitmq_management rabbitmq_prometheus

# 4. Usuário de aplicação
sudo rabbitmqctl add_user videobox 123456 || true
sudo rabbitmqctl set_permissions -p / videobox ".*" ".*" ".*"
sudo rabbitmqctl set_user_tags videobox administrator

# 5. Usuário somente leitura opcional
# sudo rabbitmqctl add_user monitor monitor123
# sudo rabbitmqctl set_user_tags monitor monitoring

echo "Dashboard: http://<IP_RABBITMQ>:15672 (user: videobox / 123456)"
